include Makefile.const

OBJ_FILES += bitmap_file_header/header.c

bitmap_file_header/header.o: bitmap_file_header/header.c bitmap_file_header/header.h
	$(CC) -c bitmap_file_header/header.c -o bitmap_file_header/header.o